### ISSUE TITLE
Submitting new records

### ISSUE THREAD

**Issue by sethtroisi** [primegap-list-project/prime-gap-list#2]
I've been running a new gap search and I'm wondering how frequently I should / could be committing records?

Would you prefer that they be bundled into monthly updates or can I (as a member of the primegap-list-project in good standing) submit them more regularly? Weekly? as I find them?

Thanks

**Comment by ghost** [comment]
I'm only the volunteer help so I have no preferences :) You may want to thrash this out with Rob, I'll point him to this thread.

**Comment by sethtroisi** [comment]
M.Jansen has been submitting daily, at some point we might want squash some of the commits but no need at this time.
